### ISSUE TITLE
[Travis Plugin] End to end test

### ISSUE THREAD

**Issue by dtuite** [RoadieHQ/backstage#1]
An end-to-end test will make it easier to confidently make changes to the plugin in the future. Instead of having to manually verify changes in the browser, the team could simply run the tests to have at least some confidence that the plugin works.

### Phase 1

 1. Load the plugin in the browser
 2. Configure authentication and other settings for a Travis project
 3. Verify that the builds show up

## Tech choices

Using the real Travis API for this purpose would probably lead to some flakey tests so it would be best to mock the Travis API with the [MSW](https://github.com/mswjs/msw) library. This is the library the backstage team plan to use for mocking ([source](https://github.com/spotify/backstage/issues/1205)).

Please use cypress (https://www.cypress.io/) to write and run the tests.

**Comment by zenway-js** [comment]
Hey David! I am trying now to write some tests for TravisCi and I've stuck with configuration of MSW since it needs to be injected as a Service Worker and I'm not sure how to do it in Backstage architecture

**Comment by dtuite** [comment]
@zenway-js ok. If you have another way to mock the requests, feel free to use that.
